name: MTierPlugin
version: '${version}'
main: com.mtier.plugin.MTierPlugin
api-version: '1.21'
commands:
  mtier:
    description: View your player statistics.
    usage: /mtier
permissions:
  mtier.use:
    description: Allows use of the /mtier command.
    default: true
